[package]
name = "rinasys-kernel"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
path = "src/lib.rs"

[[bin]]
name = "kernel"
path = "src/kmain.rs"

[dependencies]
rinasys-config-schema = { path = "../crates/config-schema" }
limine = "0.x"

[build-dependencies]
rinasys-config-codegen = { path = "../crates/config-codegen" }
