timeout: 0

/RinaSys
    protocol: limine
    path: boot():/boot/kernel.elf
    # loglevel options:
    # - error -> only error messages are printed
    # - warn -> error and warning messages are printed
    # - info -> previous and info messages are printed
    # - debug -> previous, and debug messages are printed
    # - trace -> all log messages are printed
    cmdline: loglevel=debug
