use std::path::{Path, PathBuf};

use xshell::{cmd, Shell};

mod flags {
    use std::path::PathBuf;

    xflags::xflags! {
        src "./src/main.rs"

        /// RinaSys build tasks.
        cmd xtask {
            /// Build kernel with compile-time TOML config.
            cmd build-kernel {
                /// Config profile name from kernel/config/*.toml or a path.
                optional --config config: PathBuf
            }
        }
    }
    // generated start
    // The following code is generated by `xflags` macro.
    // Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
    #[derive(Debug)]
    pub struct Xtask {
        pub subcommand: XtaskCmd,
    }

    #[derive(Debug)]
    pub enum XtaskCmd {
        BuildKernel(BuildKernel),
    }

    #[derive(Debug)]
    pub struct BuildKernel {
        pub config: Option<PathBuf>,
    }

    impl Xtask {
        #[allow(dead_code)]
        pub fn from_env_or_exit() -> Self {
            Self::from_env_or_exit_()
        }

        #[allow(dead_code)]
        pub fn from_env() -> xflags::Result<Self> {
            Self::from_env_()
        }

        #[allow(dead_code)]
        pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
            Self::from_vec_(args)
        }
    }
    // generated end
}

fn main() {
    let flags = flags::Xtask::from_env_or_exit();

    if let Err(error) = run(flags) {
        eprintln!("xtask: {error}");
        std::process::exit(1);
    }
}

fn run(flags: flags::Xtask) -> xshell::Result<()> {
    let sh = Shell::new()?;

    match flags.subcommand {
        flags::XtaskCmd::BuildKernel(flags) => {
            let config = flags.config.unwrap_or_else(|| PathBuf::from("default"));
            build_kernel(&sh, &config)
        }
    }
}

fn build_kernel(sh: &Shell, config: &Path) -> xshell::Result<()> {
    let config = sh.current_dir().join(config_path(config));

    cmd!(sh, "cargo build --manifest-path kernel/Cargo.toml")
        .env("RINASYS_KERNEL_CONFIG", config)
        .run()
}

fn config_path(value: &Path) -> PathBuf {
    if value.extension().is_some() || value.components().count() > 1 {
        value.to_path_buf()
    } else {
        PathBuf::from("kernel/config")
            .join(value)
            .with_extension("toml")
    }
}
